package io.github.agentsusagetray.companion;

import java.net.InetAddress;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.io.UnsupportedEncodingException;
import java.util.Locale;
import java.util.ArrayList;
import java.util.List;

final class EndpointParser {
    static final class ParsedEndpoint {
        final String pairingUrl;
        final String baseUrl;
        final String displayName;

        ParsedEndpoint(String pairingUrl, String baseUrl, String displayName) {
            this.pairingUrl = pairingUrl;
            this.baseUrl = baseUrl;
            this.displayName = displayName;
        }
    }

    private EndpointParser() {}

    static List<ParsedEndpoint> parseAll(String input) {
        if (input == null || input.trim().isEmpty()) {
            throw new IllegalArgumentException("Paste the pairing link generated by the desktop app.");
        }
        URI outer = parseUri(input.trim());
        List<ParsedEndpoint> endpoints = new ArrayList<>();
        if (!"agents-usage".equalsIgnoreCase(outer.getScheme())) {
            endpoints.add(parse(input));
            return endpoints;
        }
        if (!"pair".equalsIgnoreCase(outer.getHost())) {
            throw new IllegalArgumentException("This Agents Usage link is not a pairing link.");
        }
        String token = queryValue(outer, "token");
        String base = queryValue(outer, "base");
        if (base != null) {
            if (token == null || !token.matches("[A-Za-z0-9._~-]{32,256}")) {
                throw new IllegalArgumentException("The pairing link has a missing or invalid token.");
            }
            endpoints.add(parse(pairingUrlForBase(base, token)));
            String fallbackBase = queryValue(outer, "fallback");
            if (fallbackBase != null && !fallbackBase.trim().isEmpty()) {
                ParsedEndpoint parsedFallback = parse(pairingUrlForBase(fallbackBase, token));
                if (!parsedFallback.baseUrl.equals(endpoints.get(0).baseUrl)) endpoints.add(parsedFallback);
            }
            return endpoints;
        }
        String primary = queryValue(outer, "url");
        if (primary == null || primary.trim().isEmpty()) {
            throw new IllegalArgumentException("The pairing link does not contain a desktop URL.");
        }
        endpoints.add(parse(primary));
        String fallback = queryValue(outer, "fallback");
        if (fallback != null && !fallback.trim().isEmpty()) {
            ParsedEndpoint parsedFallback = parse(fallback);
            if (!parsedFallback.baseUrl.equals(endpoints.get(0).baseUrl)) endpoints.add(parsedFallback);
        }
        return endpoints;
    }

    private static String pairingUrlForBase(String input, String token) {
        URI base = parseUri(input.trim());
        if (base.getRawQuery() != null || base.getFragment() != null) {
            throw new IllegalArgumentException("The desktop address in the pairing link is invalid.");
        }
        String text = base.toASCIIString();
        if (!text.endsWith("/")) text += "/";
        String path = base.getRawPath();
        if (path == null || path.isEmpty()) path = "/";
        if (!path.endsWith("/")) path += "/";
        try {
            return text + "pair?token=" + token + "&path=" + URLEncoder.encode(path, "UTF-8");
        } catch (UnsupportedEncodingException error) {
            throw new IllegalArgumentException("The pairing link contains invalid encoding.");
        }
    }

    static ParsedEndpoint parse(String input) {
        if (input == null || input.trim().isEmpty()) {
            throw new IllegalArgumentException("Paste the pairing link generated by the desktop app.");
        }

        String candidate = input.trim();
        URI uri = parseUri(candidate);
        if ("agents-usage".equalsIgnoreCase(uri.getScheme())) {
            if (!"pair".equalsIgnoreCase(uri.getHost())) {
                throw new IllegalArgumentException("This Agents Usage link is not a pairing link.");
            }
            candidate = queryValue(uri, "url");
            if (candidate == null || candidate.trim().isEmpty()) {
                throw new IllegalArgumentException("The pairing link does not contain a desktop URL.");
            }
            uri = parseUri(candidate);
        }

        String scheme = lower(uri.getScheme());
        if (!"http".equals(scheme) && !"https".equals(scheme)) {
            throw new IllegalArgumentException("Pairing links must use HTTP or HTTPS.");
        }
        if (uri.getHost() == null || uri.getRawAuthority() == null || uri.getUserInfo() != null) {
            throw new IllegalArgumentException("The pairing link has an invalid desktop address.");
        }
        if (uri.getFragment() != null) {
            throw new IllegalArgumentException("The pairing link must not contain a fragment.");
        }
        if (uri.getPort() < -1 || uri.getPort() > 65535) {
            throw new IllegalArgumentException("The pairing link has an invalid port.");
        }

        String path = uri.getRawPath();
        if (path == null || !path.endsWith("/pair") || path.toLowerCase(Locale.ROOT).contains("%2e")
                || path.contains("//") || !path.equals(uri.normalize().getRawPath())) {
            throw new IllegalArgumentException("Use the exact pairing link printed by the desktop app.");
        }
        String token = queryValue(uri, "token");
        if (token == null || !token.matches("[A-Za-z0-9._~-]{32,256}")) {
            throw new IllegalArgumentException("The pairing link has a missing or invalid token.");
        }
        if ("http".equals(scheme) && !isPrivateHttpHost(uri.getHost())) {
            throw new IllegalArgumentException("HTTP is allowed only for private LAN or Tailscale IP addresses. Use HTTPS for hostnames.");
        }

        String prefix = path.substring(0, path.length() - "pair".length());
        String baseUrl = scheme + "://" + uri.getRawAuthority() + prefix;
        String displayName = uri.getHost() + (uri.getPort() == -1 ? "" : ":" + uri.getPort());
        return new ParsedEndpoint(uri.toASCIIString(), baseUrl, displayName);
    }

    static boolean belongsToBase(String candidate, String baseUrl) {
        try {
            URI url = new URI(candidate);
            URI base = new URI(baseUrl);
            if (!lower(url.getScheme()).equals(lower(base.getScheme()))) return false;
            if (url.getRawAuthority() == null || base.getRawAuthority() == null
                    || !url.getRawAuthority().equalsIgnoreCase(base.getRawAuthority())) return false;
            String urlPath = url.getRawPath() == null ? "/" : url.getRawPath();
            String basePath = base.getRawPath() == null ? "/" : base.getRawPath();
            return urlPath.startsWith(basePath);
        } catch (URISyntaxException error) {
            return false;
        }
    }

    private static URI parseUri(String input) {
        try {
            return new URI(input);
        } catch (URISyntaxException error) {
            throw new IllegalArgumentException("The pairing link is not a valid URL.");
        }
    }

    private static String queryValue(URI uri, String wantedKey) {
        String rawQuery = uri.getRawQuery();
        if (rawQuery == null) return null;
        String found = null;
        for (String part : rawQuery.split("&")) {
            String[] pair = part.split("=", 2);
            String key = decode(pair[0]);
            if (!wantedKey.equals(key)) continue;
            if (found != null || pair.length != 2) {
                throw new IllegalArgumentException("The pairing link contains duplicate values.");
            }
            found = decode(pair[1]);
        }
        return found;
    }

    private static String decode(String value) {
        try {
            return URLDecoder.decode(value, "UTF-8");
        } catch (IllegalArgumentException | UnsupportedEncodingException error) {
            throw new IllegalArgumentException("The pairing link contains invalid encoding.");
        }
    }

    private static String lower(String value) {
        return value == null ? "" : value.toLowerCase(Locale.ROOT);
    }

    private static boolean isPrivateHttpHost(String host) {
        String normalized = lower(host);
        if ("localhost".equals(normalized) || normalized.endsWith(".local")) return true;

        int[] ipv4 = parseIpv4(normalized);
        if (ipv4 != null) {
            return ipv4[0] == 10
                    || (ipv4[0] == 172 && ipv4[1] >= 16 && ipv4[1] <= 31)
                    || (ipv4[0] == 192 && ipv4[1] == 168)
                    || ipv4[0] == 127
                    || (ipv4[0] == 169 && ipv4[1] == 254)
                    || (ipv4[0] == 100 && ipv4[1] >= 64 && ipv4[1] <= 127);
        }

        if (!normalized.contains(":")) return false;
        try {
            InetAddress address = InetAddress.getByName(normalized);
            byte[] bytes = address.getAddress();
            return address.isLoopbackAddress() || address.isLinkLocalAddress() || address.isSiteLocalAddress()
                    || (bytes.length == 16 && (bytes[0] & 0xfe) == 0xfc);
        } catch (Exception error) {
            return false;
        }
    }

    private static int[] parseIpv4(String host) {
        String[] parts = host.split("\\.", -1);
        if (parts.length != 4) return null;
        int[] result = new int[4];
        for (int index = 0; index < parts.length; index++) {
            if (parts[index].isEmpty() || !parts[index].matches("[0-9]{1,3}")) return null;
            try {
                result[index] = Integer.parseInt(parts[index]);
            } catch (NumberFormatException error) {
                return null;
            }
            if (result[index] > 255) return null;
        }
        return result;
    }
}
